name: banana
pagerduty:
  apikey: foobar
interval: 60
disks:
  - path: /
    threshold: 80
    for: 3600
load:
  threshold: 2
  for: 300
memory:
  threshold: 80
  for: 300
services:
  services:
    - nginx
  for: 300